### ISSUE TITLE
Docker Linux installation failure

### ISSUE THREAD

**Issue by mattmazzola** [ngrok/ngrok-docs#560]
From the docs: [Installation -> Linux -> Install via Apt](https://ngrok.com/download)

```docker
# Install ngrok
RUN curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
  sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
  echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
  sudo tee /etc/apt/sources.list.d/ngrok.list && \
  sudo apt update && sudo apt install ngrok
```

This was previously working, but is now failing due to
```
2.419 E: The repository 'https://ngrok-agent.s3.amazonaws.com buster InRelease' is not signed.
```

Perhaps a certificate expired and needs to be udpated?

## Full stack trace

```text
  64 |     # Install ngrok
  65 | >>> RUN curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
[2024-01-17T19:51:09.261Z]   66 | >>>   sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
  67 | >>>   echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
  68 | >>>   sudo tee /etc/apt/sources.list.d/ngrok.list && \
  69 | >>>   sudo apt update && sudo apt install ngrok
  70 |     
--------------------
ERROR: failed to solve: process "bash -c curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc |   sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null &&   echo \"deb https://ngrok-agent.s3.amazonaws.com buster main\" |   sudo tee /etc/apt/sources.list.d/ngrok.list &&   sudo apt update && sudo apt install ngrok" did not complete successfully: exit code: 100
[2024-01-17T19:51:09.270Z] Stop (89273 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-REDMOND.mattm/container-features/0.54.1-1705520975616/Dockerfile-with-features -t vsc-projectwillow-811852a0e088c5d93246b1f1483978ff1a356407c84e386db185f5b04071abb7 --target dev_containers_target_stage --no-cache --pull --build-context dev_containers_feature_content_source=/tmp/devcontainercli-REDMOND.mattm/container-features/0.54.1-1705520975616 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=vscode --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/mattm/ProjectWillow
[2024-01-17T19:51:10.611Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-REDMOND.mattm/container-features/0.54.1-1705520975616/Dockerfile-with-features -t vsc-projectwillow-811852a0e088c5d93246b1f1483978ff1a356407c84e386db185f5b04071abb7 --target dev_containers_target_stage --no-cache --pull --build-context dev_containers_feature_content_source=/tmp/devcontainercli-REDMOND.mattm/container-features/0.54.1-1705520975616 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=vscode --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/mattm/ProjectWillow
[2024-01-17T19:51:10.611Z]     at Y$ (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:463:1860)
[2024-01-17T19:51:10.611Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-01-17T19:51:10.611Z]     at async Fw (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1831)
[2024-01-17T19:51:10.611Z]     at async $J (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:608)
[2024-01-17T19:51:10.611Z]     at async tAA (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2024-01-17T19:51:10.611Z]     at async CC (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2024-01-17T19:51:10.611Z]     at async NeA (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2024-01-17T19:51:10.611Z]     at async MeA (/home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2024-01-17T19:51:10.620Z] Stop (94714 ms): Run: /home/mattm/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node /home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-831e8d1f-1bf4-4f06-b8c6-8dbab5cbc48e1705520971176 --workspace-folder /home/mattm/ProjectWillow --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/mattm/ProjectWillow --id-label devcontainer.config_file=/home/mattm/ProjectWillow/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/mattm/ProjectWillow/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-17T19:51:10.620Z] Exit code 1
[2024-01-17T19:51:10.622Z] Command failed: /home/mattm/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node /home/mattm/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-831e8d1f-1bf4-4f06-b8c6-8dbab5cbc48e1705520971176 --workspace-folder /home/mattm/ProjectWillow --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/mattm/ProjectWillow --id-label devcontainer.config_file=/home/mattm/ProjectWillow/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/mattm/ProjectWillow/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-17T19:51:10.622Z] Exit code 1
```

**Comment by russorat** [comment]
thank you for reporting, sorry for the delay in responding. this has been fixed:

```
root@8493fba870ed:/# curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
  tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
  echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
  tee /etc/apt/sources.list.d/ngrok.list && \
  apt update && apt install ngrok
deb https://ngrok-agent.s3.amazonaws.com buster main
Get:1 https://ngrok-agent.s3.amazonaws.com buster InRelease [20.3 kB]
Hit:2 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
Get:4 https://ngrok-agent.s3.amazonaws.com buster/main arm64 Packages [3224 B]
Hit:5 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
Fetched 23.5 kB in 1s (30.1 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
21 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ngrok
0 upgraded, 1 newly installed, 0 to remove and 21 not upgraded.
Need to get 5744 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://ngrok-agent.s3.amazonaws.com buster/main arm64 ngrok arm64 3.5.0 [5744 kB]
Fetched 5744 kB in 1s (7251 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package ngrok.
(Reading database ... 4975 files and directories currently installed.)
Preparing to unpack .../archives/ngrok_3.5.0_arm64.deb ...
Unpacking ngrok (3.5.0) ...
Setting up ngrok (3.5.0) ...```
